### ISSUE TITLE
Get django-pusherable on PyPI

### ISSUE THREAD

**Issue by leggetter** [pusher/django-pusherable#2]
The docs and blog post say `pip install django-pusherable` but that won't work right now.

**Comment by aaronbassett** [comment]
Hey @leggetter it is all setup as a package ready to be uploaded. I've left that for Pusher to do otherwise it will be under my pypi account. 

It should be as simple as running 

```bash
python setup.py register
python setup.py sdist upload
```

You can check the package installs correctly before uploading by running 

```bash
python setup.py install
```
 within the root folder, or you can try installing it from Git with pip

```bash
pip install -e git@github.com:pusher/django-pusherable.git
```

**Comment by leggetter** [comment]
@aaronbassett I uploaded yesterday prior to the blog post https://pypi.python.org/pypi/django-pusherable

However, I think I've missed a compilation step for the README. Will look into that for the next version.
